# Auto-generated by build_protected.py -- do not edit manually.
import os
import sys

# -- Baked-in environment variables ------------------------------------------
_BAKED = {
    "AGENTMAX_WHOP_KEY": "",
    "AGENTMAX_LICENSE_SERVER": "",
    "AGENTMAX_SERVER_PUBKEY": "",
}
for _k, _v in _BAKED.items():
    if _v and not os.environ.get(_k):
        os.environ[_k] = _v

# -- PyArmor bootstrap --------------------------------------------------------
if getattr(sys, "frozen", False):
    try:
        import pyarmor_runtime  # noqa: F401
    except ImportError:
        pass
